
public class admin extends javax.swing.JFrame {

   
    public admin() {
        initComponents();
        setSize(1000,600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        booking = new javax.swing.JButton();
        train = new javax.swing.JButton();
        train1 = new javax.swing.JButton();
        passenger = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(44, 44, 44));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(44, 44, 44));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Admin Panel");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 290, 61));

        booking.setBackground(new java.awt.Color(204, 204, 204));
        booking.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        booking.setText("View Booking Table");
        booking.setBorderPainted(false);
        booking.setOpaque(true);
        booking.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingActionPerformed(evt);
            }
        });
        jPanel1.add(booking, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 220, 60));

        train.setBackground(new java.awt.Color(204, 204, 204));
        train.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        train.setText("Edit Train Table");
        train.setBorderPainted(false);
        train.setOpaque(true);
        train.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trainActionPerformed(evt);
            }
        });
        jPanel1.add(train, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 220, 60));

        train1.setBackground(new java.awt.Color(204, 204, 204));
        train1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        train1.setText("Edit Journey Table");
        train1.setBorderPainted(false);
        train1.setOpaque(true);
        train1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                train1ActionPerformed(evt);
            }
        });
        jPanel1.add(train1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 220, 60));

        passenger.setBackground(new java.awt.Color(204, 204, 204));
        passenger.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        passenger.setText("View Passenger Table");
        passenger.setBorderPainted(false);
        passenger.setOpaque(true);
        passenger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passengerActionPerformed(evt);
            }
        });
        jPanel1.add(passenger, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 170, -1, 60));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setText("Log Out");
        jButton1.setBorderPainted(false);
        jButton1.setOpaque(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 100, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(317, 0, 680, 690));

        jLabel2.setBackground(new java.awt.Color(111, 107, 107));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon("/Users/atharvaghodmare/Downloads/administrator.png")); // NOI18N
        jLabel2.setOpaque(true);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 320, 690));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new First_page().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void passengerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passengerActionPerformed
       
        new view_pass().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_passengerActionPerformed

    private void trainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trainActionPerformed
        new view_train().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_trainActionPerformed

    private void bookingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingActionPerformed
        new view_book().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bookingActionPerformed

    private void train1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_train1ActionPerformed
         new view_journey().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_train1ActionPerformed

    
    public static void main(String args[]) {
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton booking;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton passenger;
    private javax.swing.JButton train;
    private javax.swing.JButton train1;
    // End of variables declaration//GEN-END:variables
}
