
import diu.swe.habib.JavaToast.JToast;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Dell
 */
public class view_journey extends javax.swing.JFrame {

    /**
     * Creates new form view_journey
     */
    public view_journey() {
        initComponents();
        setSize(1000,600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sc = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table1 = new javax.swing.JTable();
        delete = new javax.swing.JButton();
        view = new javax.swing.JButton();
        add = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        journey = new javax.swing.JTextField();
        scc = new javax.swing.JTextField();
        dc = new javax.swing.JTextField();
        dept = new javax.swing.JTextField();
        arr = new javax.swing.JTextField();
        jid = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sc.setBackground(new java.awt.Color(44, 44, 44));
        sc.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table1.setBackground(new java.awt.Color(44, 44, 44));
        table1.setForeground(new java.awt.Color(255, 255, 255));
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Journey_ID", "Train_ID", "Source City", "Destination City", "Departure", "Arrival"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table1.setSelectionBackground(new java.awt.Color(255, 0, 0));
        table1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(table1);

        sc.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 750, 276));

        delete.setBackground(new java.awt.Color(204, 204, 204));
        delete.setText("Delete");
        delete.setBorderPainted(false);
        delete.setOpaque(true);
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });
        sc.add(delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 100, -1));

        view.setBackground(new java.awt.Color(204, 204, 204));
        view.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        view.setText("View");
        view.setBorderPainted(false);
        view.setContentAreaFilled(false);
        view.setOpaque(true);
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        sc.add(view, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 50, -1, -1));

        add.setBackground(new java.awt.Color(204, 204, 204));
        add.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        add.setText("Add");
        add.setBorderPainted(false);
        add.setOpaque(true);
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        sc.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 460, 100, -1));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        sc.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 94, 40));

        jLabel1.setBackground(new java.awt.Color(44, 44, 44));
        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 40)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Edit Journey Table");
        jLabel1.setOpaque(true);
        sc.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 460, 61));

        tid.setBackground(new java.awt.Color(44, 44, 44));
        tid.setForeground(new java.awt.Color(255, 255, 255));
        tid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        tid.setCaretColor(new java.awt.Color(255, 255, 255));
        sc.add(tid, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 480, 80, -1));

        jLabel2.setBackground(new java.awt.Color(44, 44, 44));
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Journey ID");
        jLabel2.setOpaque(true);
        sc.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 440, 100, 30));

        jLabel3.setBackground(new java.awt.Color(44, 44, 44));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Train ID");
        jLabel3.setOpaque(true);
        sc.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 440, 60, 30));

        jLabel4.setBackground(new java.awt.Color(44, 44, 44));
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Source City");
        jLabel4.setOpaque(true);
        sc.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, 90, 30));

        jLabel5.setBackground(new java.awt.Color(44, 44, 44));
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Destination City");
        jLabel5.setOpaque(true);
        sc.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, 110, 30));

        jLabel6.setBackground(new java.awt.Color(44, 44, 44));
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Departure");
        jLabel6.setOpaque(true);
        sc.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 440, 70, 30));

        jLabel7.setBackground(new java.awt.Color(44, 44, 44));
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Arrival");
        jLabel7.setOpaque(true);
        sc.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 440, 120, 30));

        jLabel11.setBackground(new java.awt.Color(44, 44, 44));
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Enter Jounery ID to delete the Record");
        jLabel11.setOpaque(true);
        sc.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 240, 50));

        journey.setBackground(new java.awt.Color(44, 44, 44));
        journey.setForeground(new java.awt.Color(255, 255, 255));
        journey.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        journey.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        journey.setCaretColor(new java.awt.Color(255, 255, 255));
        journey.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                journeyActionPerformed(evt);
            }
        });
        sc.add(journey, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 170, 30));

        scc.setBackground(new java.awt.Color(44, 44, 44));
        scc.setForeground(new java.awt.Color(255, 255, 255));
        scc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        scc.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        scc.setCaretColor(new java.awt.Color(255, 255, 255));
        sc.add(scc, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 480, 80, -1));

        dc.setBackground(new java.awt.Color(44, 44, 44));
        dc.setForeground(new java.awt.Color(255, 255, 255));
        dc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dc.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        dc.setCaretColor(new java.awt.Color(255, 255, 255));
        sc.add(dc, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 480, 80, -1));

        dept.setBackground(new java.awt.Color(44, 44, 44));
        dept.setForeground(new java.awt.Color(255, 255, 255));
        dept.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        dept.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        dept.setCaretColor(new java.awt.Color(255, 255, 255));
        dept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptActionPerformed(evt);
            }
        });
        sc.add(dept, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 480, 80, -1));

        arr.setBackground(new java.awt.Color(44, 44, 44));
        arr.setForeground(new java.awt.Color(255, 255, 255));
        arr.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        arr.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        arr.setCaretColor(new java.awt.Color(255, 255, 255));
        sc.add(arr, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 480, 80, -1));

        jid.setBackground(new java.awt.Color(44, 44, 44));
        jid.setForeground(new java.awt.Color(255, 255, 255));
        jid.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jid.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jid.setCaretColor(new java.awt.Color(255, 255, 255));
        sc.add(jid, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 80, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1103, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sc, javax.swing.GroupLayout.DEFAULT_SIZE, 591, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new admin().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        DefaultTableModel model = (DefaultTableModel)table1.getModel();

        try 
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/railway", "root", "atharva13"); 
            Statement stmt = con.createStatement();
            String query = "Select * from journey where CURDATE()<departure ;";
            ResultSet rs = stmt.executeQuery(query);
            while(rs.next())
            {
                int jid = rs.getInt("journey_id");
                int tid = rs.getInt("train_id");
                String sname = rs.getString("source_name");
                String dname = rs.getString("destination_name");
                String ddate = rs.getString("departure");
                String adate = rs.getString("arrival");
                model.addRow(new Object[]{jid,tid,sname,dname,ddate,adate});
            }            
        }

        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_viewActionPerformed

    private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
      try 
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/railway", "root", "atharva13"); 
             Statement stmt = (Statement)con.createStatement();
            int journey1 = Integer.parseInt(journey.getText());
            stmt.executeUpdate("delete from journey where journey_id = '"+journey1+"'");
        }
                catch(Exception e)
         {
             JOptionPane.showMessageDialog(null,e);
         }

        DefaultTableModel model = (DefaultTableModel)table1.getModel();
        int rows = model.getRowCount();
        if(rows>0)
        {
            for(int i=0;i<rows;i++)
            {
                model.removeRow(0);
            }
        } 
        new JToast().makeToast(this, "Value Deleted",1);  
        journey.setText("");
    }//GEN-LAST:event_deleteActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
      
        DefaultTableModel model = (DefaultTableModel)table1.getModel();try 
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/railway", "root", "atharva13"); 
            int jid1 = Integer.parseInt(jid.getText());
            int tid1 = Integer.parseInt(tid.getText());
            String sc1 = scc.getText();
            String dc1 = dc.getText();
            String dept1 = dept.getText();
            String arr1 = arr.getText();
            
            CallableStatement cstmt = con.prepareCall("{call add_journey(?, ?, ?, ?, ? ,?)}");
            cstmt.setInt(1, jid1);
            cstmt.setInt(2,tid1);
            cstmt.setString(3,sc1);
            cstmt.setString(4,dc1);
            cstmt.setString(5,dept1);
            cstmt.setString(6,arr1);
            cstmt.executeUpdate();
        }
                catch(Exception e)
         {
             JOptionPane.showMessageDialog(null,e);
         }

        
        int rows = model.getRowCount();
        if(rows>0)
        {
            for(int i=0;i<rows;i++)
            {
                model.removeRow(0);
            }
        }
         new JToast().makeToast(this, "Value Inserted",1);  
         jid.setText("");
         tid.setText("");
         scc.setText("");
         dc.setText("");
         dept.setText("");
         arr.setText("");
         
    }//GEN-LAST:event_addActionPerformed

    private void deptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deptActionPerformed

    private void journeyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_journeyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_journeyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view_journey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view_journey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view_journey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view_journey.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view_journey().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JTextField arr;
    private javax.swing.JTextField dc;
    private javax.swing.JButton delete;
    private javax.swing.JTextField dept;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jid;
    private javax.swing.JTextField journey;
    private javax.swing.JPanel sc;
    private javax.swing.JTextField scc;
    private javax.swing.JTable table1;
    private javax.swing.JTextField tid;
    private javax.swing.JButton view;
    // End of variables declaration//GEN-END:variables
}
